Move card and translation closer to center of page
darren-lester/KanaTab pull request #1
Opened 2017-04-14 07:23 UTC by mysticuno

Whenever I open a new tab, I almost immediately start typing my next search into the omnibar. Because of this, however, the kana I'm looking at ends up getting covered by my search suggestions:

![image](https://cloud.githubusercontent.com/assets/6826622/25036379/7b895f76-20c1-11e7-92d3-d8f9852ae146.png)

By moving both the card and the translation to the center, we can avoid the kana being covered by the search suggestions.

![image](https://cloud.githubusercontent.com/assets/6826622/25036406/9b73f738-20c1-11e7-9ef7-6737382dac2b.png)

2017-04-14 18:55 UTC, darren-lester requested changes
Could we keep the translation at 80% from the top? I like having a little more space between the kana and translation.

2017-04-14 18:58 UTC, darren-lester commented
Thanks for the pull request. I see your point it is definitely better to push the flashcard down a little lower to avoid being covered by the suggestions! If you are happy to keep the translation a little lower down I'll merge the request.

2017-04-14 19:55 UTC, mysticuno commented
Sure! Moving it back so that now it looks like this:

![image](https://cloud.githubusercontent.com/assets/6826622/25054356/a99f99b6-212a-11e7-903d-49bb5d559fde.png)

2017-04-15 09:31 UTC, darren-lester approved these changes

2017-04-15 09:31 UTC, merged